export default {
    background:require('../../app/images/background.png'),
    backgroundChat:require('../../app/images/background-chat-v2.jpg'),
    backgroundLogin:require('../../app/images/background-login.png'),
    backgroundPincode:require('../../app/images/background-pincode.png'),

    icoAkasicExchanes:require('../../app/images/ico-akasic-exchanes.png'),
    icoAkasicGame:require('../../app/images/ico-akasic-game.png'),
    icoAkasicMovingStore:require('../../app/images/ico-akasic-moving-store.png'),
    icoAkasicSeller:require('../../app/images/ico-akasic-seller.png'),
    icoAkasicTrade:require('../../app/images/ico-akasic-trade.png'),

    icoComposePostLink:require('../../app/images/ico-compose-post-link.png'),
    icoComposePostPhoto:require('../../app/images/ico-compose-post-photo.png'),
    icoComposePostRecord:require('../../app/images/ico-compose-post-record.png'),
    icoComposePostSticker:require('../../app/images/ico-compose-post-sticker.png'),
    icoComposePostVideo:require('../../app/images/ico-compose-post-video.png'),

    icoTabAkasicActive:require('../../app/images/ico-tab-akasic-active.png'),
    icoTabAkasic:require('../../app/images/ico-tab-akasic.png'),
    icoTabChatsActive:require('../../app/images/ico-tab-chats-active.png'),
    icoTabChats:require('../../app/images/ico-tab-chats.png'),
    icoTabContactActive:require('../../app/images/ico-tab-contact-active.png'),
    icoTabContact:require('../../app/images/ico-tab-contact.png'),
    icoTabFundActive:require('../../app/images/ico-tab-fund-active.png'),
    icoTabFund:require('../../app/images/ico-tab-fund.png'),
    icoTabHomeActive:require('../../app/images/ico-tab-home-active.png'),
    icoTabHome:require('../../app/images/ico-tab-home.png'),

    icoAttach:require('../../app/images/ico-attach.png'),
    icoBackWhite:require('../../app/images/ico-back-white.png'),
    icoBack:require('../../app/images/ico-back.png'),
    icoBlueMinus:require('../../app/images/ico-blue-minus.png'),
    icoChecked:require('../../app/images/ico-checked.png'),
    icoComment:require('../../app/images/ico-comment.png'),

    icoCurrencyBTC:require('../../app/images/ico-currency-btc.png'),
    icoCurrencyETH:require('../../app/images/ico-currency-eth.png'),
    icoCurrencyMASHT:require('../../app/images/ico-currency-masht.png'),
    
    icoHookChat:require('../../app/images/ico-hook-chat.png'),
    icoHookChatFriend:require('../../app/images/ico-hook-chat-friend.png'),
    icoBell:require('../../app/images/ico-bell.png'),
    icoMenu:require('../../app/images/ico-menu.png'),
    icoEdit:require('../../app/images/ico-edit.png'),
    icoFind:require('../../app/images/ico-find.png'),
    icoFindBlue:require('../../app/images/ico-find-blue.png'),
    icoDone:require('../../app/images/ico-done.png'),
    icoGreenPlus:require('../../app/images/ico-green-plus.png'),
    icoWhitePlus:require('../../app/images/ico-white-plus.png'),
    icoBluePlus:require('../../app/images/ico-blue-plus.png'),
    icoHeartActive:require('../../app/images/ico-heart-active.png'),
    icoGroup:require('../../app/images/ico-create-group.png'),
    icoAskQuestion:require('../../app/images/ico-ask-question.png'),
    icoSpeechBubble:require('../../app/images/ico-speech-bubble.png'),
    icoTelephone:require('../../app/images/ico-telephone.png'),
    icoSticker:require('../../app/images/ico-sticker.png'),
    icoNotification:require('../../app/images/ico-notification.png'),
    icoSecure:require('../../app/images/ico-secure.png'),
    icoProfile:require('../../app/images/ico-profile.png'),
    icoBigEye:require('../../app/images/ico-big-eye.png'),
    icoLanguage:require('../../app/images/ico-language.png'),
    icoDrawer:require('../../app/images/ico-drawer.png'),
    icoSecretChat:require('../../app/images/ico-new-secret-chat.png'),
    icoChannel:require('../../app/images/ico-new-channel.png'),

    icoHeart:require('../../app/images/ico-heart.png'),
    icoLetter:require('../../app/images/ico-letter.png'),
    icoCheckMark:require('../../app/images/ico-check-mark.png'),
    icoLock:require('../../app/images/ico-lock.png'),
    icoMobile:require('../../app/images/ico-mobile.png'),
    icoPickSticker:require('../../app/images/ico-pick-sticker.png'),
    icoPostPhoto:require('../../app/images/ico-post-photo.png'),
    icoPostVideo:require('../../app/images/ico-post-video.png'),
    icoSend:require('../../app/images/ico-send.png'),
    icoWhiteSend:require('../../app/images/ico-white-send.png'),
    
    icoShare:require('../../app/images/ico-share.png'),
    icoSort:require('../../app/images/ico-sort.png'),
    icoLocation:require('../../app/images/ico-location.png'),
    icoTag:require('../../app/images/ico-tag.png'),
    icoFacebook:require('../../app/images/ico-facebook.png'),
    icoTakePhoto:require('../../app/images/ico-take-photo.png'),
    icoUncheck:require('../../app/images/ico-uncheck.png'),
    icoUser:require('../../app/images/ico-user.png'),
    LogoGray:require('../../app/images/logo-gray.png'),
    Logo:require('../../app/images/logo.png'),

}